In [1]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\admin\anaconda3\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [6]:
#Series

s = pd.Series([1, 2, 3, 4, 5])
print(s)
print(type(s))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [7]:
print(s[0])
print(s[2])

1
3

In [8]:
s = pd.Series([23, 24, 25, 26], index=["Adam", "Bob", "Charlie", "Dude"])
print(s)

Adam       23
Bob        24
Charlie    25
Dude       26
dtype: int64

In [9]:
print(s["Adam"])
print(s["Dude"])

23
26

In [10]:
print(s.index)

Index(['Adam', 'Bob', 'Charlie', 'Dude'], dtype='object')

In [13]:
#Dataframe

info = {
    "Name" : ["Krushna", "Ketan", "Rohit"],
    "Age" : [20, 21, 19],
    "CGPA" : [8.32, 8.0, 7.75]
}

df = pd.DataFrame(info)
print(df)
print(type(df))
print(df.index)
print(df.columns)

      Name  Age  CGPA
0  Krushna   20  8.32
1    Ketan   21  8.00
2    Rohit   19  7.75
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [14]:
df

      Name  Age  CGPA
0  Krushna   20  8.32
1    Ketan   21  8.00
2    Rohit   19  7.75

In [18]:
df = pd.DataFrame([["Adam", 23], ["Bob", 24], ["Charlie", 25]], columns=["Name", "Age"])

print(df)

      Name  Age
0     Adam   23
1      Bob   24
2  Charlie   25

In [20]:
df

      Name  Age
0     Adam   23
1      Bob   24
2  Charlie   25

In [21]:
import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6]])

df = pd.DataFrame(np_arr, columns=["A", "B", "C"])

print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [22]:
# CSV data 

df = pd.read_csv("employee_data.csv")
print(df, type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [23]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [24]:
# Dataframe Methods

print(df.head()) #starting 5 rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [25]:
print(df.tail()) #last 5 rows

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [26]:
print(df.head(2))

   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000
1   2    Bob   32         IT   72000

In [28]:
print(df.sample())
print(df.sample(3))

   ID Name  Age Department  Salary
4   5  Eva   38         IT   65000
   ID   Name  Age Department  Salary
6   7  Grace   41         HR   82000
5   6  Frank   29    Finance   50000
0   1  Alice   25         HR   55000

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [34]:
df.shape

(10, 5)

In [35]:
df.describe()

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [37]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [38]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64