In [57]:
import pandas as pd

In [18]:
df = pd.read_csv("raw_data.csv")

In [19]:
df2 = df.copy()

df2["tax"] = df2["income"].apply(lambda x : "20%" if x >= 60000 else "10%")

df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  10%
1    1      John Doe  29.0     USA     Male  55000.0  10%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  10%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  10%

In [20]:
gender_map = {"Male" : "M", "Female" : "F", "Unknown": "U"}
df2["gender"] = df2["gender"].map(gender_map)

df2

    id          name   age country gender   income  tax
0    1      John Doe  29.0     USA      M  55000.0  10%
1    1      John Doe  29.0     USA      M  55000.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0  20%
3    3          Alex   NaN     USA      U  47000.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN  10%
5    5        Li Wei  27.0   China      M  51000.0  10%
6    6           NaN  45.0   India      F  73000.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%
8    8    Rachel Lee  29.0     USA      F  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%

In [21]:
df2 = df2.assign(new_income = df["income"] * 1.1)

In [22]:
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
1    1      John Doe  29.0     USA      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN     USA      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA    NaN  58000.0  10%     63800.0

In [23]:
df2["country"] = df2["country"].replace("USA", "US")

In [24]:
df2

    id          name   age country gender   income  tax  new_income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

In [25]:
df2.columns = ["Id", "Name", "Age", "Country", "Gender", "Income", "Tax", "New_Income"]

In [26]:
df2

    Id          Name   Age Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

In [27]:
df2.rename(columns={"Income":"Salary"})

    Id          Name   Age Country Gender   Salary  Tax  New_Income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

In [28]:
df2.rename(index={1:"First"})

       Id          Name   Age Country Gender   Income  Tax  New_Income
0       1      John Doe  29.0      US      M  55000.0  10%     60500.0
First   1      John Doe  29.0      US      M  55000.0  10%     60500.0
2       2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3       3          Alex   NaN      US      U  47000.0  10%     51700.0
4       4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5       5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6       6           NaN  45.0   India      F  73000.0  20%     80300.0
7       7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8       8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9       9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10     10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

In [29]:
df2.sort_values("Income")

    Id          Name   Age Country Gender   Income  Tax  New_Income
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN

In [30]:
df2.sort_values("Income", ascending=False)

    Id          Name   Age Country Gender   Income  Tax  New_Income
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN

In [32]:
df2.sort_values(["Income", "Age"])

    Id          Name   Age Country Gender   Income  Tax  New_Income
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN

In [33]:
df2.sort_index()

    Id          Name   Age Country Gender   Income  Tax  New_Income
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0

In [36]:
df2["Ranking"] = df2["Income"].rank(ascending=False, method="max")

In [37]:
df2

    Id          Name   Age Country Gender   Income  Tax  New_Income  Ranking
0    1      John Doe  29.0      US      M  55000.0  10%     60500.0      7.0
1    1      John Doe  29.0      US      M  55000.0  10%     60500.0      7.0
2    2    Jane Smith   NaN  Canada      F  62000.0  20%     68200.0      4.0
3    3          Alex   NaN      US      U  47000.0  10%     51700.0      9.0
4    4  Maria Garcia  34.0   Spain      F      NaN  10%         NaN      NaN
5    5        Li Wei  27.0   China      M  51000.0  10%     56100.0      8.0
6    6           NaN  45.0   India      F  73000.0  20%     80300.0      1.0
7    7    Ahmed Khan  38.0     NaN      M  68000.0  20%     74800.0      2.0
8    8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0      4.0
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0  10%     49500.0     10.0
10  10   Emily Davis  31.0      US    NaN  58000.0  10%     63800.0      5.0

In [38]:
df2[["Id", "Name", "Age", "Country", "Gender", "Income", "New_Income", "Tax"]]

    Id          Name   Age Country Gender   Income  New_Income  Tax
0    1      John Doe  29.0      US      M  55000.0     60500.0  10%
1    1      John Doe  29.0      US      M  55000.0     60500.0  10%
2    2    Jane Smith   NaN  Canada      F  62000.0     68200.0  20%
3    3          Alex   NaN      US      U  47000.0     51700.0  10%
4    4  Maria Garcia  34.0   Spain      F      NaN         NaN  10%
5    5        Li Wei  27.0   China      M  51000.0     56100.0  10%
6    6           NaN  45.0   India      F  73000.0     80300.0  20%
7    7    Ahmed Khan  38.0     NaN      M  68000.0     74800.0  20%
8    8    Rachel Lee  29.0      US      F  62000.0     68200.0  20%
9    9   Carlos Ruiz   NaN  Mexico      M  45000.0     49500.0  10%
10  10   Emily Davis  31.0      US    NaN  58000.0     63800.0  10%

In [39]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [43]:
df.groupby("country")["income"].mean()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       55400.0
Name: income, dtype: float64

In [44]:
df.groupby("country")["income"].max()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       62000.0
Name: income, dtype: float64

In [45]:
df.groupby("country")["income"].min()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       47000.0
Name: income, dtype: float64

In [47]:
df.groupby("gender")["income"].mean()

gender
Female     65666.666667
Male       54800.000000
Unknown    47000.000000
Name: income, dtype: float64

In [48]:
df.groupby("country")["income"].agg(["mean", "min", "max"])

            mean      min      max
country
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        NaN      NaN      NaN
USA      55400.0  47000.0  62000.0

In [49]:
df.groupby("country")["income"].agg(avgsal="mean", minsal="min", maxsal="max")

          avgsal   minsal   maxsal
country
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        NaN      NaN      NaN
USA      55400.0  47000.0  62000.0

In [55]:
df.groupby("country").agg(
    maxincome = ("income", "max"),
    avgage = ("age", "mean")
)

         maxincome  avgage
country
Canada     62000.0     NaN
China      51000.0    27.0
India      73000.0    45.0
Mexico     45000.0     NaN
Spain          NaN    34.0
USA        62000.0    29.5

In [61]:
df = pd.DataFrame({
    "country" : ["USA", "USA", "India", "India"],
    "year" : [2020, 2021, 2020, 2021],
    "sales" : [100, 120, 90, 110],
    "profit" : [20, 25, 18, 22],
    "tax" : [10, 20, 30, 40]
})

In [62]:
df

  country  year  sales  profit  tax
0     USA  2020    100      20   10
1     USA  2021    120      25   20
2   India  2020     90      18   30
3   India  2021    110      22   40

In [63]:
melted_df = df.melt(
    id_vars=["country", "year"],
    value_vars=["sales", "profit", "tax"],
    var_name="metrics",
    value_name="value"
)

In [64]:
melted_df

   country  year metrics  value
0      USA  2020   sales    100
1      USA  2021   sales    120
2    India  2020   sales     90
3    India  2021   sales    110
4      USA  2020  profit     20
5      USA  2021  profit     25
6    India  2020  profit     18
7    India  2021  profit     22
8      USA  2020     tax     10
9      USA  2021     tax     20
10   India  2020     tax     30
11   India  2021     tax     40

In [65]:
df_customers = pd. DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Adam", "Bob", "Charlie", "Dave"]
})

df_orders = pd. DataFrame({
    "order_id": [101, 102, 103, 104],
    "customer_id": [2, 1, 4, 5],
    "amount": [250, 120, 300, 180]
})

In [66]:
df_customers

   customer_id     name
0            1     Adam
1            2      Bob
2            3  Charlie
3            4     Dave

In [67]:
df_orders

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     300
3       104            5     180

In [68]:
pd.merge(df_customers, df_orders, on="customer_id")

   customer_id  name  order_id  amount
0            1  Adam       102     120
1            2   Bob       101     250
2            4  Dave       103     300

In [69]:
pd.merge(df_customers, df_orders, on="customer_id", how="left")

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0

In [70]:
pd.merge(df_customers, df_orders, on="customer_id", how="right")

   customer_id  name  order_id  amount
0            2   Bob       101     250
1            1  Adam       102     120
2            4  Dave       103     300
3            5   NaN       104     180

In [71]:
pd.merge(df_customers, df_orders, on="customer_id", how="outer")

   customer_id     name  order_id  amount
0            1     Adam     102.0   120.0
1            2      Bob     101.0   250.0
2            3  Charlie       NaN     NaN
3            4     Dave     103.0   300.0
4            5      NaN     104.0   180.0

In [72]:
df1 = pd. DataFrame({
    "id" : [1, 2, 3],
    "name" : ["Adam", "Eve", "Bob"]
})
df2 = pd.DataFrame({
    "id" : [4, 5, 6],
    "name" : ["Charlie", "Fester", "Gilian"]
})

In [73]:
df1

   id  name
0   1  Adam
1   2   Eve
2   3   Bob

In [74]:
df2

   id     name
0   4  Charlie
1   5   Fester
2   6   Gilian

In [75]:
pd.concat([df1, df2])

   id     name
0   1     Adam
1   2      Eve
2   3      Bob
0   4  Charlie
1   5   Fester
2   6   Gilian

In [76]:
pd.concat([df2, df1])

   id     name
0   4  Charlie
1   5   Fester
2   6   Gilian
0   1     Adam
1   2      Eve
2   3      Bob

In [77]:
pd.concat([df1, df2], axis=1)

   id  name  id     name
0   1  Adam   4  Charlie
1   2   Eve   5   Fester
2   3   Bob   6   Gilian